version: "3.1"

volumes:
  db: {}
  cache: {}

services:
  db:
    image: postgres:11.2
    container_name: db
    hostname: "db"
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_DB: trivia
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.0-rc1
    container_name: cache
    hostname: "cache"
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: queue
    hostname: "queue"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "queue"
    # volumes:
    #   - ./db/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  envoy:
    image: envoyproxy/envoy-dev:c3e4a00ed3fcb7d07fbe6c8c655a2f4949a67da3
    container_name: proxy
    ports:
      - "9901:9901"
      - "9001:9001"
    volumes:
      - ./.infra/envoy.yaml:/etc/envoy/envoy.yaml
