version: "3"

volumes:
  db: {}

networks:
  proxy: {}

services:
  db:
    image: postgres:11.2
    container_name: db
    hostname: "db"
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_DB: trivia
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  envoy:
    image: envoyproxy/envoy-dev:c3e4a00ed3fcb7d07fbe6c8c655a2f4949a67da3
    container_name: proxy
    networks:
      - proxy
    ports:
      - "9901:9901"
      - "9001:9001"
    volumes:
      - ./.infra/envoy.local.yaml:/etc/envoy/envoy.yaml
  # qb:
  #   hostname: qb-dev
  #   restart: unless-stopped
  #   build:
  #     context: ./apps/qb
  #     dockerfile: Dockerfile
  #     target: dev
  #   command:
  #     ["./scripts/wait-for-it.sh", "db:5432", "--", "python", "/app/run.py"]
  #   environment:
  #     DEBUG: "true"
  #     PORT: "8000"
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: appuser
  #     DB_PASSWORD: appuser
  #   volumes:
  #     - ./scripts:/scripts
  #     - ./apps/qb:/app
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - "db"
  #   depends_on:
  #     - "db"
  # client:
  #   hostname: client-dev
  #   restart: unless-stopped
  #   build:
  #     context: ./apps/client
  #     dockerfile: Dockerfile
  #     target: dev
  #   command: ["./scripts/wait-for-it.sh", "qb:8000", "--", "yarn", "dev"]
  #   environment:
  #     NODE_ENV: "development"
  #     PORT: "3000"
  #   volumes:
  #     - ./scripts:/scripts
  #     - ./apps/client:/app
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - "qb"
  #   depends_on:
  #     - "qb"
  # streaming:
  #   hostname: streaming-dev
  #   restart: unless-stopped
  #   build:
  #     context: ./apps/streaming
  #     dockerfile: Dockerfile
  #   environment:
  #     GO_ENV: "development"
  #     PORT: "9000"
  #   networks:
  #     - proxy
  #   volumes:
  #     - ./apps/streaming:/app
  #   ports:
  #     - "9000:9000"
  #   links:
  #     - "envoy"
  #   depends_on:
  #     - "envoy"
