version: "3.1"

volumes:
  db: {}

services:
  db:
    image: postgres:11.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_DB: trivia
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
