// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: QuestionOption.proto

package server

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OptionKey int32

const (
	OptionKey_A OptionKey = 0
	OptionKey_B OptionKey = 1
	OptionKey_C OptionKey = 2
	OptionKey_D OptionKey = 3
)

// Enum value maps for OptionKey.
var (
	OptionKey_name = map[int32]string{
		0: "A",
		1: "B",
		2: "C",
		3: "D",
	}
	OptionKey_value = map[string]int32{
		"A": 0,
		"B": 1,
		"C": 2,
		"D": 3,
	}
)

func (x OptionKey) Enum() *OptionKey {
	p := new(OptionKey)
	*p = x
	return p
}

func (x OptionKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionKey) Descriptor() protoreflect.EnumDescriptor {
	return file_QuestionOption_proto_enumTypes[0].Descriptor()
}

func (OptionKey) Type() protoreflect.EnumType {
	return &file_QuestionOption_proto_enumTypes[0]
}

func (x OptionKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionKey.Descriptor instead.
func (OptionKey) EnumDescriptor() ([]byte, []int) {
	return file_QuestionOption_proto_rawDescGZIP(), []int{0}
}

type QuestionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   OptionKey `protobuf:"varint,1,opt,name=key,proto3,enum=pq.qb.questions.option.OptionKey" json:"key,omitempty"`
	Title string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *QuestionOption) Reset() {
	*x = QuestionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuestionOption_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionOption) ProtoMessage() {}

func (x *QuestionOption) ProtoReflect() protoreflect.Message {
	mi := &file_QuestionOption_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionOption.ProtoReflect.Descriptor instead.
func (*QuestionOption) Descriptor() ([]byte, []int) {
	return file_QuestionOption_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionOption) GetKey() OptionKey {
	if x != nil {
		return x.Key
	}
	return OptionKey_A
}

func (x *QuestionOption) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_QuestionOption_proto protoreflect.FileDescriptor

var file_QuestionOption_proto_rawDesc = []byte{
	0x0a, 0x14, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x71, 0x2e, 0x71, 0x62, 0x2e, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5b,
	0x0a, 0x0e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x33, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x70, 0x71, 0x2e, 0x71, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2a, 0x27, 0x0a, 0x09, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x05, 0x0a, 0x01, 0x41, 0x10, 0x00, 0x12,
	0x05, 0x0a, 0x01, 0x42, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x43, 0x10, 0x02, 0x12, 0x05, 0x0a,
	0x01, 0x44, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QuestionOption_proto_rawDescOnce sync.Once
	file_QuestionOption_proto_rawDescData = file_QuestionOption_proto_rawDesc
)

func file_QuestionOption_proto_rawDescGZIP() []byte {
	file_QuestionOption_proto_rawDescOnce.Do(func() {
		file_QuestionOption_proto_rawDescData = protoimpl.X.CompressGZIP(file_QuestionOption_proto_rawDescData)
	})
	return file_QuestionOption_proto_rawDescData
}

var file_QuestionOption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_QuestionOption_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_QuestionOption_proto_goTypes = []interface{}{
	(OptionKey)(0),         // 0: pq.qb.questions.option.OptionKey
	(*QuestionOption)(nil), // 1: pq.qb.questions.option.QuestionOption
}
var file_QuestionOption_proto_depIdxs = []int32{
	0, // 0: pq.qb.questions.option.QuestionOption.key:type_name -> pq.qb.questions.option.OptionKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_QuestionOption_proto_init() }
func file_QuestionOption_proto_init() {
	if File_QuestionOption_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_QuestionOption_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QuestionOption_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QuestionOption_proto_goTypes,
		DependencyIndexes: file_QuestionOption_proto_depIdxs,
		EnumInfos:         file_QuestionOption_proto_enumTypes,
		MessageInfos:      file_QuestionOption_proto_msgTypes,
	}.Build()
	File_QuestionOption_proto = out.File
	file_QuestionOption_proto_rawDesc = nil
	file_QuestionOption_proto_goTypes = nil
	file_QuestionOption_proto_depIdxs = nil
}
