"""answer_bank foreign key relationship

Revision ID: 4ece8aa41dfe
Revises: 989b989bf0ca
Create Date: 2020-12-25 09:58:24.093368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece8aa41dfe'
down_revision = '989b989bf0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answer_bank', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer_bank', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_bank', type_='foreignkey')
    op.drop_constraint(None, 'answer_bank', type_='foreignkey')
    # ### end Alembic commands ###
