"""answr_bank display_name and id fix

Revision ID: 54e7ffa940de
Revises: 4ece8aa41dfe
Create Date: 2020-12-26 10:44:30.895064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e7ffa940de'
down_revision = '4ece8aa41dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_bank', sa.Column('display_name', sa.String(), nullable=True))
    op.execute("UPDATE answer_bank SET display_name = ''")
    op.alter_column('answer_bank', 'display_name', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_bank', 'display_name')
    # ### end Alembic commands ###
