"""answer_bank

Revision ID: 989b989bf0ca
Revises: c2cee10e456e
Create Date: 2020-12-25 09:54:03.889743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b989bf0ca'
down_revision = 'c2cee10e456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_bank_id'), 'answer_bank', ['id'], unique=False)
    op.alter_column('games', 'is_started',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'is_started',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_answer_bank_id'), table_name='answer_bank')
    op.drop_table('answer_bank')
    # ### end Alembic commands ###
