name: Linting
on: [push, pull_request]
jobs:
  streaming_lint:
    runs-on: ubuntu-latest
    env:
      streaming-dir: ./apps/streaming
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15.6"
      - name: Vendor
        working-directory: ${{env.streaming-dir}}
        run: |
          go mod vendor
      - name: Run GoLint
        working-directory: ${{env.streaming-dir}}
        run: |
          make lint
  client_lint:
    runs-on: ubuntu-latest
    env:
      client-dir: ./apps/client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "15.5"
      - name: Install Dependencies
        working-directory: ${{env.client-dir}}
        run: |
          yarn install
      - name: Run Yarn linting
        working-directory: ${{env.client-dir}}
        run: |
          yarn lint
